Add gerd image for jetson
caretech-owl/hive-builder pull request #9
Opened 2024-12-04 14:30 UTC by costrau

2025-01-30 18:01 UTC, aleneum requested changes

2025-01-30 18:01 UTC, aleneum commented on images/gerd-jetson/Dockerfile
> +ENV GERD_VERSION="v0.5.6"
Could you try v0.6.0 here?

2025-01-30 18:01 UTC, aleneum commented on images/gerd-jetson/Dockerfile
> +RUN sed -i 's/torch>=2.5.1/torch>=2.5.0/g' gerd/pyproject.toml
GERD 0.6.0 hopefully makes this obsolete

2025-01-30 18:01 UTC, aleneum commented on images/gerd-jetson/Dockerfile
> +RUN ln -s /usr/bin/python3 /usr/bin/python
this linkage can be omitted when python3 is called as an entrypoint directy OR -- to save a layer -- this could be && to the previous RUN command

2025-01-30 18:02 UTC, aleneum commented on images/gerd-jetson/Dockerfile
> +RUN sed -i 's/torch>=2.5.1/torch>=2.5.0/g' gerd/pyproject.toml
since pydantic env variables are case insensitive we could change gerd_lora_output_dir -> GERD_LORA_OUTPUT_DIR . This is a matter of style. Pro: env variables are usually capitalized, con: keeping them lowercase implies their usage as an override for pydantic-settings

2025-01-30 18:05 UTC, aleneum commented
furthermore: I think it's good practise to keep the version in line with the used gerd version. I'd suggest a release `
release(gerd-jetson): 0.6.0`

2025-01-30 19:07 UTC, costrau commented on images/gerd-jetson/Dockerfile
> +RUN sed -i 's/torch>=2.5.1/torch>=2.5.0/g' gerd/pyproject.toml
Then we would need to change that for the regular gerd image, too. What would you prefer?

2025-01-30 19:08 UTC, costrau commented on images/gerd-jetson/Dockerfile
> +RUN ln -s /usr/bin/python3 /usr/bin/python
the gerd router also calls python, so we indeed need that link, but I will use && as you suggest

2025-01-30 20:23 UTC, costrau commented on images/gerd-jetson/Dockerfile
> +RUN sed -i 's/torch>=2.5.1/torch>=2.5.0/g' gerd/pyproject.toml
left it lower-case for the time being

2025-01-31 07:57 UTC, aleneum commented on images/gerd-jetson/Dockerfile
> +RUN ln -s /usr/bin/python3 /usr/bin/python
i push gerd 0.6.1 with 'sys.executable' instead of 'python'. Give this a try.

2025-01-31 08:49 UTC, costrau commented on images/gerd-jetson/Dockerfile
> +RUN ln -s /usr/bin/python3 /usr/bin/python
Works like a charm

2025-01-31 08:50 UTC, aleneum approved these changes

2025-01-31 08:58 UTC, merged